### ISSUE TITLE
Needs 6.0.0 NetCore

### ISSUE THREAD

**Issue by ThePotato97** [metatablecat/DisableBetaApp#2]
The version in release needs 6.0.0 (x86) NetCore from https://dotnet.microsoft.com/en-us/download/dotnet/6.0/runtime?cid=getdotnetcore which isn't mentioned in the readme

**Comment by metatablecat** [comment]
I was aware of this already but I can target releases with it packaged in, except the output is in the megabytes

Will attach it anyway.

**Comment by metatablecat** [comment]
I found a better compromise that shouldn't need any active runtimes nor produce a really large executable (its still 12MB lol)
